services:
  app:
    build: .
    container_name: my_node_app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    networks:
      - my_network
    volumes:
      - .:/usr/src/app

  db:
    image: postgres:15
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_DB_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  pgdata:

networks:
  my_network:
